### PR TITLE
Standalone traitlets

### PR DESCRIPTION
**Pull request by richafrank**
Updated to standalone traitlets package

### CODE REVIEW

**Comment by ssanderson** [comment]
Do we need IPython >= 2.4.0 in the requirements any more after this?

**Comment by ssanderson** [comment]
Changes look good to me.  Had one comment about possibly extraneous dependencies.

**Comment by richafrank** [comment]
> Do we need IPython >= 2.4.0 in the requirements any more after this?

I'll investigate.

**Comment by richafrank** [comment]
Tests still pass without IPython.  Will remove and merge.

**Comment by ssanderson** [comment]
:+1:

**Pull request closed without merging**
